name: net_app_env
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - bzip2=1.0.8
  - ca-certificates
  - icu
  - libexpat
  - libffi
  - liblzma
  - libsqlite
  - libzlib
  - ncurses
  - openssl=3.6.1
  - packaging
  - pip
  - readline
  - setuptools
  - tk
  - tzdata
  - wheel
  - pip:
    - Flask==3.1.2
    - Flask-Login==0.6.3
    - Flask-SQLAlchemy==3.1.1
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - SQLAlchemy==2.0.46
    - Werkzeug==3.1.5
    - black==26.1.0
    - blinker==1.9.0
    - click==8.3.1
    - dnspython==2.8.0
    - email-validator==2.3.0
    - idna==3.11
    - itsdangerous==2.2.0
    - mypy_extensions==1.1.0
    - pathspec==1.0.4
    - platformdirs==4.5.1
    - python-dotenv==1.2.1
    - pytokens==0.4.1
    - ruff==0.15.0
    - typing_extensions==4.15.0
